apiVersion: v1
kind: Secret
metadata:
  name: pics-secrets
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: Mapeo_2026
  DATABASE_URL: postgresql://postgres:Mapeo_2026@35.225.173.28:5432/baches_db
  MINIO_ROOT_USER: postgres
  MINIO_ROOT_PASSWORD: postgres
  MINIO_PUBLIC_URL: "http://35.194.31.183:9000"
