apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: keda-escala-preprocesamiento
spec:
  scaleTargetRef:
    name: worker-preprocesamiento 
  minReplicaCount: 0             # Si no hay videos, se apaga (0)
  maxReplicaCount: 3
  cooldownPeriod: 1800            # Son 30 minutoss 
  triggers:
  - type: redis
    metadata:
      address: redis-queue.default.svc.cluster.local:6379
      listName: "cola_preprocesamiento"
      listLength: "1"            # 1 pod por cada video en cola
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: keda-escala-inferencia
spec:
  scaleTargetRef:
    name: worker-inferencia      
  minReplicaCount: 0             
  maxReplicaCount: 4
  cooldownPeriod: 1800              # Son 30 minutoss
  triggers:
  - type: redis
    metadata:
      address: redis-queue.default.svc.cluster.local:6379
      listName: "cola_inferencia"
      listLength: "1"            # 1 pod por cada tarea pendiente