name: Deploy API to GKE
on:
  push:
    branches:
      - main
    paths:
      - 'api/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Autenticación en Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Configurar Docker para GCP
      run: gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Conectar al Clúster de Kubernetes (GKE)
      uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name: 'pics-cluster'
        location: 'us-central1-a'

    - name: Build y Push de la imagen
      run: |
        cd api
        IMAGE_TAG="us-central1-docker.pkg.dev/pics-moreno-cloud/pics-repo/api-fastapi:v-${GITHUB_SHA::7}"

        docker build -t $IMAGE_TAG .
        docker push $IMAGE_TAG

    - name: Desplegar en Kubernetes
      run: |
        IMAGE_TAG="us-central1-docker.pkg.dev/pics-moreno-cloud/pics-repo/api-fastapi:v-${GITHUB_SHA::7}"
        kubectl set image deployment/api-fastapi "*=$IMAGE_TAG"
